### ISSUE TITLE
Add scala-steward to project

### ISSUE THREAD

**Issue by zakpatterson** [pauljamescleary/scala-pet-store#110]
Scala Steward automatically submits PRs for upgrading dependencies. 

Example PR by scala steward:
https://github.com/typelevel/cats/pull/2660

Many typelevel projects use it:
https://github.com/fthomas/scala-steward/blob/master/repos.md

**Comment by pauljamescleary** [comment]
Nice, looks great, I will have to use it in some other projects

**Comment by pauljamescleary** [comment]
Oof, the steward is going nuts!

**Comment by zakpatterson** [comment]
Yeah once we're up to speed it should be quieter, plus having an open PR for each upstream update that we're in conflict with is great.

Each time we merge any PR tho, N travis builds will start up for each individual outstanding steward PR. 

Since you've merged a few, and we've seen the steward go ahead and update it's unmerged PRs, I'll close this.
