### ISSUE TITLE
Switch to circe-config

### ISSUE THREAD

**Issue by zakpatterson** [pauljamescleary/scala-pet-store#120]
For consistency, we should use circe-config instead of pureconfig.

**Comment by zakpatterson** [comment]
I don't think there could be any measurable advantage, it just seems like a more natural choice for this project since we're already using circe. Also c-c doesn't do kebab-case which seemed weird to me. Here's a line where I used it in another project, although we wouldn't need to use all the ApplicativeAsk complexity here:

https://github.com/clovellytech/http4s-modules/blob/master/src/main/scala/h4sm/package.scala#L16

**Comment by zakpatterson** [comment]
I went ahead and did it, let me know what you think.

**Comment by franklinchou** [comment]
This was closed by #123, no?

**Comment by zakpatterson** [comment]
Fixed with #123, thanks @franklinchou !
