### ISSUE TITLE
Travis is not connected

### ISSUE THREAD

**Issue by zakpatterson** [pauljamescleary/scala-pet-store#125]
At: https://travis-ci.org/pauljamescleary/scala-pet-store
Getting the message:

We couldn't find the repository 
pauljamescleary/scala-pet-store

**Comment by zakpatterson** [comment]
Ah. I wasn't aware of the difference. You want to reconnect .com then and I'll update the readme

**Comment by pauljamescleary** [comment]
I have to test .com. I already switched.

**Comment by pauljamescleary** [comment]
Looks like it worked!  https://travis-ci.com/pauljamescleary/scala-pet-store/builds/97153970
