### ISSUE TITLE
add Scala 2.13 crossbuild

### ISSUE THREAD

**Issue by SethTisue** [pauljamescleary/scala-pet-store#141]
I can easily imagine you have dependencies that aren't published for 2.13.0-M5 yet, but adding the cross build and seeing where it gets stuck would be a way to find out what's missing and then we can go nag those maintainers

**Comment by SethTisue** [comment]
hmm, one obvious blocker is going to be http4s

maybe subscribe to https://github.com/http4s/http4s/issues/2025 and once that one gets closed as fixed, swing into action?

**Comment by pauljamescleary** [comment]
@SethTisue can definitely run a quick test to see what issues we will have

**Comment by pauljamescleary** [comment]
@SethTisue  - FYI - https://github.com/pauljamescleary/scala-pet-store/pull/142
