### ISSUE TITLE
Thanks note and request for an note

### ISSUE THREAD

**Issue by kunjee17** [pauljamescleary/scala-pet-store#192]
Hi, 
I like to thank for wonderful project. I am new to Scala and specially type level eco system. And it really helps a lot. 

One request. Is there any not explaining architecture or point of view author. In most part I do get it what is going on, but it would be great to know point of view of author. 

It is non-blocking issue so please don't mind to close it if request don't come under feasibility criteria.

**Comment by zakpatterson** [comment]
Hi @kunjee17, [a bit of documentation about the overall design considerations are here](https://github.com/pauljamescleary/scala-pet-store#what-is-going-on-here), if there's something specific you would like to see, or something that is missing, please feel free to update the issue (documentation PRs no matter how small are also welcome). Thanks for the nice words, we're happy to see this project is helpful.
