### ISSUE TITLE
Add Update User Endpoint

### ISSUE THREAD

**Issue by pauljamescleary** [pauljamescleary/scala-pet-store#20]
https://github.com/ariesprayoga/swagger-java-sample-app/blob/master/src/main/java/com/wordnik/swagger/sample/resource/UserResource.java

**Comment by daddykotex** [comment]
I think this is already implemented but usually the update on a REST interface looks a little bit like:
`PUT /users/{username}`

That seems to be the case for the API described in the URL you shared. Do you want the scala-pet-store to be similar, because currently, it is not.

**Comment by pauljamescleary** [comment]
Good point @daddykotex, I am unclear if we have to keep in sync with that project.  I would be more interested to know if we were correct by REST standards and do what is appropriate there.

I think `PUT /users/username` is correct as the username is the unique key for users.

Probably worthwhile to open an issue and make that small change

**Comment by pauljamescleary** [comment]
Looks like that was following the PET endpoint, so we should be consistent in all places where we do an update.

**Comment by daddykotex** [comment]
👍

**Comment by pauljamescleary** [comment]
Closed by #74
