### ISSUE TITLE
Remove unnecessary `unsafeRunSync` 

### ISSUE THREAD

**Issue by SystemFw** [pauljamescleary/scala-pet-store#39]
First of all, apologies for not sending a PR directly.

In any case, there is an `unsafeRunSync` in `Server` to go from `F[Stream[F, A]]` to `Stream[F, A]`: this is unnecessary, prefer `Stream.force(FofStream)` instead.

Even better, avoid having `F[Stream[F, A]]` in the first place, and instead lift the actions returning `F` into Stream using `Stream.eval`, and have the whole `for` be in `Stream`. The reason for this is to allow creation of resources with `Stream.bracket`, which takes a finaliser and guarantees resource safety, and it's a very useful and common pattern when dealing with resources that e.g. need to be closed or cleaned up.

**Comment by pauljamescleary** [comment]
Good recommendation, will look into it, thanks!

**Comment by SystemFw** [comment]
Since we're at it, another thing that jumped to the eye is redundant constraints, e.g. `[F[_]: Sync](implicit M: Effect[F])` . This is redundant because an `Effect` is already a `Sync` so there's no need for multiple constraints. That being said, ideally one should seek out opportunities to reduce the power of one's constraints, e.g. not use `Effect` when only `Sync` will do. Also, using `M: Effect[F]` is somewhat unusual (apologies if it's intended). Normally the type class evidence is named after the type parameter (`F: Sync[F]`) so that it looks like you are calling methods "on the type" when you do e.g. `F.delay`

P.S. Hope you don't mind the suggestions

**Comment by pauljamescleary** [comment]
@SystemFw most definitely welcome the feedback.  I will look at the Sync v. Effect thing.  I believe HTTP4s in it's latest incarnation requires `Effect`.  I will review and eliminate redundancy as well as use the least powerful constraint
